sudo: no
cache:
  directories:
    - $HOME/.cache/pip
language: python
python: "2.7"

install: ./scripts/travis-setup.sh
script: ./scripts/test.sh

notifications:
  webhooks: http://leeroybot.lonnen.com/hubot/travis?room=%23breakpad
