sudo: no
cache:
  directories:
    - $HOME/.cache/pip
language: python
python: "2.7"

before_install: ./scripts/pipstrap.py
install: pip install -r requirements.txt
script: ./scripts/test.sh

notifications:
  webhooks: http://leeroybot.lonnen.com/hubot/travis?room=%23breakpad
