# docker-compose for socorro-collector
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  appbase:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - crashes:/crashes

  web:
    extends:
      service: appbase
    ports:
      - "8000:8000"
    command: ./scripts/run_web.sh

  crashmover:
    environment:
      - S3_USE_SIGV4=True
    extends:
      service: appbase
    links:
      - rabbitmq
      - fakes3
    command: ./scripts/run_crashmover.sh

  # FIXME: do statsd
  # statsd:

  rabbitmq:
    # https://hub.docker.com/_/rabbitmq/
    # FIXME: pin this to the version of rabbitmq we're using in -stage
    # and -prod
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpwd
      - RABBITMQ_DEFAULT_VHOST=rabbitvhost

  fakes3:
    # https://hub.docker.com/r/lphoward/fake-s3/
    image: lphoward/fake-s3
    ports:
      - "4569:4569"

volumes:
  crashes:
